baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'OSR October'
theme = 'ananke'

[params]
  body_classes = "baskervvile bg-near-white"
  post_content_classes = "baskervvile bg-near-white"
  # I don't use commento, but I use the commento partial
  commentoEnable = true
  custom_css = ["css/custom.css"]
